- hosts: wordpress 
  become: true
  vars:
    wp_version: 5.7.1
    wp_webserver: nginx
    wp_mysql_db: "wpdatabase"
    wp_mysql_user: "wpadmin"
    wp_mysql_password: "mysql_pass"
    wp_mysql_host: "mariadb-server.jobs.fr"
    wp_mysql_ip: "{{ hostvars[wp_mysql_host]['ansible_default_ipv4']['address'] }}"
    wp_mysql_collate: ''
    wp_mysql_charset: 'utf8'
    wp_admin_email: "admin@jobs.fr"
    wp_sitename: "test.com"
    wp_install_dir: "/var/www/test.com"
     
  roles:
    - wordpress

- hosts: mysql
  become: true
  vars:
    wp_mysql_db: "wpdatabase"
    wp_mysql_user: "wpadmin"
    wp_mysql_password: "mysql_pass"
    wp_host: "wordpress-server.jobs.fr"
    wp_ip: "{{ hostvars[wp_host]['ansible_default_ipv4']['address'] }}"
  roles:
   - mysql
